# SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0
# Copyright (c) 2026 NVIDIA CORPORATION. All rights reserved.

Summary: NVIDIA SW and HW steering dump parser
Name: mlx-steering-dump
Version: 26.04.001
Release: 0%{?_dist}
License: GPLv2 or BSD
Url: https://github.com/Mellanox/mlx_steering_dump
Source: https://github.com/Mellanox/mlx_steering_dump/releases/download/v%{version}/%{name}-%{version}.tar.gz
Vendor: NVIDIA
Requires: python3
%global __python python3
%description
NVIDIA SW and HW steering dump parser and triggering tool.
Parses CSV dump files generated by software and hardware steering
in NVIDIA ConnectX and BlueField devices.

%prep
%setup -q %{name}-%{version}

%install
install -d %{buildroot}/usr/share/mlx-steering-dump/sws/src/parsers
install -d %{buildroot}/usr/share/mlx-steering-dump/hws/src
install -d %{buildroot}/usr/bin/
install -d %{buildroot}%{_mandir}/man1

install -m 755 sws/mlx_steering_dump_parser.py  %{buildroot}/usr/share/mlx-steering-dump/sws
install -m 644 sws/src/*.py  %{buildroot}/usr/share/mlx-steering-dump/sws/src/
install -m 644 sws/src/parsers/*.py  %{buildroot}/usr/share/mlx-steering-dump/sws/src/parsers/
install -m 755 sws/mlx_steering_dump %{buildroot}/usr/bin/

install -m 755 hws/mlx_hw_steering_parser.py  %{buildroot}/usr/share/mlx-steering-dump/hws
install -m 644 hws/src/*.py  %{buildroot}/usr/share/mlx-steering-dump/hws/src/
install -m 755 hws/mlx_hw_steering_dump %{buildroot}/usr/bin/

install -m 644 debian/mlx_steering_dump.1 %{buildroot}%{_mandir}/man1/

%clean

%preun


%files
/usr/share/mlx-steering-dump/*
/usr/bin/mlx_steering_dump
/usr/bin/mlx_hw_steering_dump
%{_mandir}/man1/mlx_steering_dump.1*

%changelog
* Wed Apr 22 2026 Yevgeny Kliteynik <kliteyn@nvidia.com>
- Update spec: set version 26.04.001

* Thu Feb 26 2026 Yevgeny Kliteynik <kliteyn@nvidia.com>
- Update spec: fix branding, license, description, manpage references

* Wed Oct 6 2021 Mohammad Kabat <mohammadkab@nvidia.com>
- Add rpm support
