.\" SPDX-License-Identifier: BSD-3-Clause
.\" Copyright (c) 2026 NVIDIA CORPORATION. All rights reserved.
.\"
.TH mlx_steering_dump 1 2026-03-01
.\"

.SH NAME
mlx_steering_dump \- HW/SW Steering dump tool

.SH DESCRIPTION
This is the HW/SW steering dump parsing tools intended for developers.

.SH USAGE

.TP
.B Hardware steering:
.B
.nf
  mlx_hw_steering_dump -h
.fi

.TP
.B Software steering:
.B
.nf
  mlx_steering_dump -h
.fi


.SH AUTHORS
Yevgeny Kliteynik <kliteyn@nvidia.com>,
Hamdan Igbaria <hamdani@nvidia.com>
